# Generated by Django 5.1.6 on 2025-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='dectption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='states',
        ),
        migrations.AddField(
            model_name='todolist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
